# 3D Transformations Calculations

## Why is this useful?
This notebook is for performing matrix transformations typically used for the forward and inverse kinematics of robot manipulators.

###### Setting up notebook with composed transformation funtions

In [72]:
from composed_transformations import forwardQ_TRPY, A_matrix
from math import sqrt
import numpy as np
from numpy import cos, deg2rad, sin, deg2rad

### Forward transformation (TRPY) Example

Calculate forward composed transformations as follows:

In [73]:
forwardQ_TRPY(-10,40,15,45,-30,0)

array([[  0.61237244,  -0.70710678,  -0.35355339,  15.        ],
       [  0.61237244,   0.70710678,  -0.35355339,  40.        ],
       [  0.5       ,   0.        ,   0.8660254 , -10.        ],
       [  0.        ,   0.        ,   0.        ,   1.        ]])

### Defining Matrices using Numpy

###### Define matrices as follows:

In [74]:
np.array([[0.7071,0.7071,0,-10],
         [0,0,1,20],
         [0.7071,-0.7071,0,-5],
         [0,0,0,1]])

array([[  0.7071,   0.7071,   0.    , -10.    ],
       [  0.    ,   0.    ,   1.    ,  20.    ],
       [  0.7071,  -0.7071,   0.    ,  -5.    ],
       [  0.    ,   0.    ,   0.    ,   1.    ]])

### A-Matrix Calculation Example

Define A-matrix as follows:

In [75]:
A_matrix(50,60,0,30)

array([[ 0.8660254 , -0.5       ,  0.        , 43.30127019],
       [ 0.5       ,  0.8660254 , -0.        , 25.        ],
       [ 0.        ,  0.        ,  1.        , 60.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

## Example Problem 1

Find (Q_21^-1) * Q_31 * pA_r3

In [76]:
np.linalg.inv(Q21) @ Q31 @ pA_r3


array([[-9.7574],
       [-8.213 ],
       [-4.    ],
       [ 1.    ]])

## Example Problem 2

Find (Q_gripbase^-1) * Q_graspbase

In [77]:
Q_gripbase = forwardQ_TRPY(40,20,150,90,0,90)
Q_graspbase = forwardQ_TRPY(-70,20,200,90,0,115)

In [78]:
np.linalg.inv(Q_gripbase) @ Q_graspbase

array([[   1.        ,    0.        ,    0.        ,    0.        ],
       [   0.        ,    0.90630779,   -0.42261826, -110.        ],
       [   0.        ,    0.42261826,    0.90630779,   50.        ],
       [   0.        ,    0.        ,    0.        ,    1.        ]])